cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('order/', views.order, name='order'),
    path('order/send/', views.OrderSendView.as_view(), name='ordersend'),
]

main/urls.py
from django.urls import path, include
from .views import *
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('shop/<slug:slug_product>/', views.product, name='product'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

zulya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

main/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Categories(models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)
    slug_category = models.SlugField(verbose_name='URL', unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Materials(models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'


class Colors(models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)
    color = models.CharField(verbose_name='Код цвета (например #FFFFFF)', max_length=7)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'


class Sizes(models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'


class Product(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    slug_product = models.SlugField(verbose_name='URL', unique=True, default=uuid.uuid1)
    category = models.ForeignKey(Categories, verbose_name='Категория', related_name='category',
                                 on_delete=models.PROTECT, blank=True, null=True)
    img = models.ImageField(verbose_name='Изображение 1', upload_to='media/products')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    materials = models.ManyToManyField(Materials, verbose_name='Материалы', related_name='materials')
    colors = models.ManyToManyField(Colors, verbose_name='Цвета', related_name='colors')
    sizes = models.ManyToManyField(Sizes, verbose_name='Размеры', related_name='sizes')
    date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('main:product_detail', args=[self.id, self.slug_product])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

cart/forms.py
from django import forms
from main.models import Product

PRODUCT_QUANTITY_CHOISES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.CharField(required=False, initial=1, widget=forms.HiddenInput)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    colors = forms.CharField(required=False, initial=False, widget=forms.RadioSelect)
    sizes = forms.CharField(required=False, initial=False, widget=forms.RadioSelect)


class OrderSendForm(forms.Form):
    name = forms.CharField()
    phone = forms.CharField()
    mail = forms.CharField(required=False)

cart/views.py
import telebot
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm, OrderSendForm

bot = telebot.TeleBot("1378421264:AAGlDLBdWr0LTbxJ6mIc2h_vXZ8YDxyQMPs")


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if cd['colors'] == '':
            cd['colors'] = 'Не задан'
        if cd['sizes'] == '':
            cd['sizes'] = 'Не задан'
        cart.add(product=product, update_quantity=cd['update'], colors=cd['colors'],
                 sizes=cd['sizes'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'cart/cart.html', context)


def order(request):
    return render(request, 'cart/order.html')


class OrderSendView(View):
    def post(self, request):
        if request.method == 'POST':
            form = OrderSendForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                phone = form.cleaned_data['phone']
                if form.cleaned_data['mail'] == '':
                    mail = 'Не указана'
                else:
                    mail = form.cleaned_data['mail']
                cart = Cart(request)
                message = 'Поступил новый заказ!\r\n\r\nИмя: ' + name + '\r\nТелефон: ' + phone + '\r\nПочта: ' \
                          + mail + '\r\n\r\nПродукты\r\n\r\n'

                for c in cart:
                    message += 'Название: ' + str(c['product']) + '\r\n'
                    message += 'Цвет: ' + c['colors'] + '\r\n'
                    message += 'Размер: ' + c['sizes'] + '\r\n'
                    message += 'Цена: ' + str(c['price']) + '\r\n\r\n'

                message += 'Общая стоимость: ' + str(cart.get_total_price())

                bot.send_message(-459836531, message)
                Cart.clear(cart)
                return redirect('cart:cart_detail')
            return redirect('index')

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Sizes
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    return render(request, 'main/index.html')


def shop(request):
    produ = Product.objects.all()
    product_list = Product.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(product_list, 10)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {
        'produ': produ,
        'products': products,
    }
    return render(request, 'main/shop.html', context)


def product(request, slug_product):
    product = get_object_or_404(Product, slug_product__iexact=slug_product)
    context = {
        'product': product,
    }
    return render(request, 'main/product-details.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, Sizes,  id=id, slug=slug)
    return render(request, 'main/product-details.html', {'product': product})


def about(request):
    return render(request, 'main/about.html')


def contact(request):
    return render(request, 'main/contact.html')

cart/templates/cart/cart.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Корзина{% endblock %}
{% block content %}

<body>
    <div class="main-wrapper">
        {% include 'header.html' %}
        {% include 'mobile-header.html' %}
        <div class="breadcrumb-area bg-img" style="background-image:url(https://demo.hasthemes.com/daxone-preview/daxone/assets/images/bg/breadcrumb.jpg);">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <h2>Страничка корзины</h2>
                    <ul>
                        <li>
                            <a href="{% url 'main:index' %}">Главная</a>
                        </li>
                        <li class="active">Корзина</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="cart-main-area pt-85 pb-90">
            <div class="container">
                <h3 class="cart-page-title">Your cart items</h3>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <form action="cart.html#">
                            <div class="table-content table-responsive cart-table-content">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Изображение</th>
                                            <th>Название продукта</th>
                                            <th>Цена продукта</th>
                                            <th>Количество</th>
                                            <th>Общая сумма</th>
                                            <th>Удалить</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for item in cart %}
                                        {% with product=item.product %}
                                        <tr>
                                            <td class="product-thumbnail">
                                                <a href="cart.html#"><img src="{{ product.img.url }}" alt="" height="98px"></a>
                                            </td>
                                            <td class="product-name"><a href="cart.html#">{{ product.name }}</a></td>
                                            <td class="product-price-cart"><span class="amount">{{ product.price }}</span></td>
                                            <td class="product-quantity">
                                                <div class="cart-plus-minus">
                                                    <input class="cart-plus-minus-box" type="text" name="qtybutton" value="2">
                                                </div>
                                            </td>
                                            <td class="product-subtotal">{{ product.price }}</td>
                                            <td class="product-remove">
                                                <a href="{% url 'cart:cart_remove' product.id %}"><i class="la la-close"></i></a>
                                            </td>
                                        </tr>
                                        {% endwith %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="cart-shiping-update-wrapper">
                                        <div class="cart-shiping-update">
                                            <a href="{% url 'main:shop' %}">Продолжить покупки</a>
                                        </div>
                                        {% for item in cart %}
                                            {% with product=item.product %}
                                                <div class="cart-clear">
                                                    <a href="{% url 'cart:cart_remove' product.id %}">Очистить корзину</a>
                                                </div>
                                            {% endwith %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="row">
                            <div class="col-lg-4 col-md-12">
                                <div class="grand-totall">
                                    <div class="title-wrap">
                                        <h4 class="cart-bottom-title section-bg-gary-cart">Итоги корзины:</h4>
                                    </div>
                                    <h5>Сумма всех товаров <span>{{ cart.get_total_price }}</span></h5>
                                    <h4 class="grand-totall-title">Итоговая сумма <span>{{ cart.get_total_price }}</span></h4>
                                    <a href="{% url 'cart:order' %}">Оформить заказ</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'footer.html' %}

        {% include 'modal_wrapper.html' %}
    </div>

</body>
{% endblock %}

main/templates/header.html
{% load static %}
<header class="header-area transparent-bar sticky-bar">
            <div class="main-header-wrap">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-3 col-lg-3">
                            <div class="logo mt-40">
                                <a href="index.html"><img class='logo__wrap' src="{% static 'images/logo/logo.png' %}" alt="logo"></a>
                            </div>
                        </div>
                        <div class="col-xl-8 col-lg-6">
                            <div class="main-menu menu-common-style menu-lh-1 menu-margin-4 menu-font-3 res-hm9-margin">
                                <nav>
                                    <ul>
                                        <li class="angle-shape"><a href="{% url 'main:index' %}">Главная</a></li>
                                        <li class="angle-shape"><a href="{% url 'main:shop' %}">Магазин </a></li>
                                        <li class="angle-shape"><a href="{% url 'main:about' %}">О нас</a>
                                        <li class="angle-shape"><a href="{% url 'cart:cart_detail' %}">Корзина</a>
                                            
                                        
                                        <li><a href="{% url 'main:contact' %}">Контакты</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-1 col-lg-3">
                            <div class="header-right-wrap mt-40">
                                <div class="cart-wrap cart-wrap-3 cart-wrap-3-white cart-wrap-hm9">
                                    <button class="cart-active">
                                        <i class="la la-shopping-cart"></i>
                                        <span class="count-style-3">01</span>
                                    </button>
                                    <div class="shopping-cart-content">
                                        <div class="shopping-cart-top">
                                            <h4>Корзина</h4>
                                            <a class="cart-close" href="index.html#"><i class="la la-close"></i></a>
                                        </div>
                                        <ul>
                                            <li class="single-shopping-cart">
                                                <div class="shopping-cart-img">
                                                    <a href="index.html#"><img alt="" src="{% static 'images/cart/cart-1.jpg' %}"></a>
                                                    <div class="item-close">
                                                        <a href="index.html#"><i class="sli sli-close"></i></a>
                                                    </div>
                                                </div>
                                                <div class="shopping-cart-title">
                                                    <h4><a href="index.html#">Корейское платье.</a></h4>
                                                    <span>$99.00</span>
                                                </div>
                                                <div class="shopping-cart-delete">
                                                    <a href="index.html#"><i class="la la-trash"></i></a>
                                                </div>
                                            </li>
                                            <li class="single-shopping-cart">
                                                <div class="shopping-cart-img">
                                                    <a href="index.html#"><img alt="" src="{% static 'images/cart/cart-2.jpg' %}"></a>
                                                    <div class="item-close">
                                                        <a href="index.html#"><i class="sli sli-close"></i></a>
                                                    </div>
                                                </div>
                                                <div class="shopping-cart-title">
                                                    <h4><a href="index.html#">Корейское платье.</a></h4>
                                                    <span>$99.00</span>
                                                </div>
                                                <div class="shopping-cart-delete">
                                                    <a href="index.html#"><i class="la la-trash"></i></a>
                                                </div>
                                            </li>
                                            <li class="single-shopping-cart">
                                                <div class="shopping-cart-img">
                                                    <a href="index.html#"><img alt="" src="{% static 'images/cart/cart-3.jpg' %}"></a>
                                                    <div class="item-close">
                                                        <a href="index.html#"><i class="sli sli-close"></i></a>
                                                    </div>
                                                </div>
                                                <div class="shopping-cart-title">
                                                    <h4><a href="index.html#">Корейское платье.</a></h4>
                                                    <span>$99.00</span>
                                                </div>
                                                <div class="shopping-cart-delete">
                                                    <a href="index.html#"><i class="la la-trash"></i></a>
                                                </div>
                                            </li>
                                        </ul>
                                        <div class="shopping-cart-bottom">
                                            <div class="shopping-cart-total">
                                                <h4>Subtotal <span class="shop-total">$290.00</span></h4>
                                            </div>
                                            <div class="shopping-cart-btn btn-hover default-btn text-center">
                                                <a class="black-color" href="checkout.html">Continue to Chackout</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-small-mobile">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <div class="mobile-logo">
                                <a href="index.html">
                                    <img alt="" src="{% static 'images/logo/logo.png' %}">
                                </a>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="header-right-wrap">
                                <div class="cart-wrap common-style">
                                    <button class="cart-active">
                                        <i class="la la-shopping-cart"></i>
                                        <span class="count-style">2 Items</span>
                                    </button>
                                    <div class="shopping-cart-content">
                                        <div class="shopping-cart-top">
                                            <h4>Your Cart</h4>
                                            <a class="cart-close" href="index.html#"><i class="la la-close"></i></a>
                                        </div>
                                        <ul>
                                            <li class="single-shopping-cart">
                                                <div class="shopping-cart-img">
                                                    <a href="index.html#"><img alt="" src="{% static 'images/cart/cart-1.jpg' {% static '"></a>
                                                    <div class="item-close">
                                                        <a href="index.html#"><i class="sli sli-close"></i></a>
                                                    </div>
                                                </div>
                                                <div class="shopping-cart-title">
                                                    <h4><a href="index.html#">Корейское платье.</a></h4>
                                                    <span>$99.00</span>
                                                </div>
                                                <div class="shopping-cart-delete">
                                                    <a href="index.html#"><i class="la la-trash"></i></a>
                                                </div>
                                            </li>
                                            <li class="single-shopping-cart">
                                                <div class="shopping-cart-img">
                                                    <a href="index.html#"><img alt="" src="{% static 'images/cart/cart-2.jpg' %}"></a>
                                                    <div class="item-close">
                                                        <a href="index.html#"><i class="sli sli-close"></i></a>
                                                    </div>
                                                </div>
                                                <div class="shopping-cart-title">
                                                    <h4><a href="index.html#">Корейское платье.</a></h4>
                                                    <span>$99.00</span>
                                                </div>
                                                <div class="shopping-cart-delete">
                                                    <a href="index.html#"><i class="la la-trash"></i></a>
                                                </div>
                                            </li>
                                            <li class="single-shopping-cart">
                                                <div class="shopping-cart-img">
                                                    <a href="index.html#"><img alt="" src="{% static 'images/cart/cart-3.jpg' %}"></a>
                                                    <div class="item-close">
                                                        <a href="index.html#"><i class="sli sli-close"></i></a>
                                                    </div>
                                                </div>
                                                <div class="shopping-cart-title">
                                                    <h4><a href="index.html#">Корейское платье.</a></h4>
                                                    <span>$99.00</span>
                                                </div>
                                                <div class="shopping-cart-delete">
                                                    <a href="index.html#"><i class="la la-trash"></i></a>
                                                </div>
                                            </li>
                                        </ul>
                                        <div class="shopping-cart-bottom">
                                            <div class="shopping-cart-total">
                                                <h4>Subtotal <span class="shop-total">$290.00</span></h4>
                                            </div>
                                            <div class="shopping-cart-btn btn-hover default-btn text-center">
                                                <a class="black-color" href="checkout.html">Continue to Chackout</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="mobile-off-canvas">
                                    <a class="mobile-aside-button" href="index.html#"><i class="la la-navicon la-2x"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

main/templates/main/contact.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Контакты{% endblock %}
{% block content %}
    <div class="main-wrapper">
        {% include 'header.html' %}
        {% include 'mobile-header.html' %}
        <div class="breadcrumb-area bg-img" style="background-image:url(https://demo.hasthemes.com/daxone-preview/daxone/assets/images/bg/breadcrumb.jpg);">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <h2>Наши контакты</h2>
                    <ul>
                        <li>
                            <a href="{% url 'main:index' %}">Главная</a>
                        </li>
                        <li class="active">Контакты </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="contact-area pt-85 pb-90">
            <div class="container">
                <div class="contact-info-wrap mb-50">
                    <h3>contact info</h3>
                    <div class="row">
                        <div class="col-lg-4 col-md-4">
                            <div class="single-contact-info text-center mb-30">
                                <i class="ti-location-pin"></i>
                                <h4>Наш адресс</h4>
                                <p>Боконбаева 105/3 </p>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="single-contact-info extra-contact-info text-center mb-30">
                                <ul>
                                    <li><i class="ti-mobile"></i> 0990-930-555 </li>
                                    <li><i class="ti-email"></i> <a href="contact.html#"> info@example.com</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="single-contact-info text-center mb-30">
                                <i class=" ti-alarm-clock"></i>
                                <h4>Рабочее время</h4>
                                <p>Пон - Пят. 9:00am - 5:00pm </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="get-in-touch-wrap">
                    <h3>Свяжитесь с нами</h3>
                    <div class="contact-from contact-shadow">
                        <form id="contact-form" action="http://whizthemes.com/mail-php/contact/mail.php" method="post">
                            <div class="row">
                                <div class="col-lg-6">
                                    <input name="name" type="text" placeholder="Имя">
                                </div>
                                <div class="col-lg-6">
                                    <input name="email" type="email" placeholder="Почта">
                                </div>
                                <div class="col-lg-12">
                                    <textarea name="message" placeholder="Комментарий"></textarea>
                                </div>
                                <div class="col-lg-12">
                                    <button class="submit" type="submit">Отправить</button>
                                </div>
                            </div>
                        </form>
                        <p class="form-messege"></p>
                    </div>
                </div>
            </div>
        </div>
        {% include 'footer.html' %}
    </div>
{% endblock %}
</html>

main/templates/main/pagination.html
<div class="pagination-style text-center">
    <ul>
        
        <li>
            {% if page.has_previous %}
            <a class="prev" href="?page={{ page.previous_page_number }}"><i class="la la-angle-left"></i></a>
            {% endif %}
        </li>
        
        <li><a class="active" href="shop-fullwide-no-sidebar.html#">01</a></li>
        <li><a href="shop-fullwide-no-sidebar.html#">02</a></li>
        <li><a href="shop-fullwide-no-sidebar.html#">03</a></li>
        <li><a href="shop-fullwide-no-sidebar.html#">04</a></li>
        <li><a href="shop-fullwide-no-sidebar.html#">05</a></li>
        <li><a href="shop-fullwide-no-sidebar.html#">06</a></li>
        
        <li>
            {% if page.has_next %}
            <a class="next" href="?page={{ page.next_page_number }}"><i class="la la-angle-right"></i></a>
         {% endif %}
     </li>
       
    </ul>
</div>